spring.application.name=proyectoFinal

# PostgreSQL
spring.datasource.url=jdbc:postgresql://dpg-d8u50ulckfvc73eop3hg-a.oregon-postgres.render.com:5432/ebtdb?sslmode=require
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Precios (solo referencia textual)
restaurante.precio.taquiza=110
restaurante.precio.loza=500
restaurante.personas-por-bitrolero=60

# Security
spring.security.user.name=admin
spring.security.user.password=admin123
spring.security.user.roles=ADMIN

# Swagger / OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.example.proyectofinal.controller
